# Generated by Django 6.0.3 on 2026-03-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_libro_anio_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
