# Generated by Django 6.0.3 on 2026-03-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='anio',
            new_name='fecha_publicacion',
        ),
    ]
