# Generated by Django 6.0.3 on 2026-03-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_libro_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.IntegerField(),
        ),
    ]
